package com.pojo;

public class ST {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.ids-t
     *
     * @mbggenerated
     */
    private Integer idsT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Susername
     *
     * @mbggenerated
     */
    private String susername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Spassword
     *
     * @mbggenerated
     */
    private String spassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Tel
     *
     * @mbggenerated
     */
    private Integer tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.QQ
     *
     * @mbggenerated
     */
    private Integer qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Sname
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.School
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Profession
     *
     * @mbggenerated
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.ids-t
     *
     * @return the value of s_t.ids-t
     *
     * @mbggenerated
     */
    public Integer getIdsT() {
        return idsT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.ids-t
     *
     * @param idsT the value for s_t.ids-t
     *
     * @mbggenerated
     */
    public void setIdsT(Integer idsT) {
        this.idsT = idsT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Susername
     *
     * @return the value of s_t.Susername
     *
     * @mbggenerated
     */
    public String getSusername() {
        return susername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Susername
     *
     * @param susername the value for s_t.Susername
     *
     * @mbggenerated
     */
    public void setSusername(String susername) {
        this.susername = susername == null ? null : susername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Spassword
     *
     * @return the value of s_t.Spassword
     *
     * @mbggenerated
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Spassword
     *
     * @param spassword the value for s_t.Spassword
     *
     * @mbggenerated
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Sex
     *
     * @return the value of s_t.Sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Sex
     *
     * @param sex the value for s_t.Sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Tel
     *
     * @return the value of s_t.Tel
     *
     * @mbggenerated
     */
    public Integer getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Tel
     *
     * @param tel the value for s_t.Tel
     *
     * @mbggenerated
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.QQ
     *
     * @return the value of s_t.QQ
     *
     * @mbggenerated
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.QQ
     *
     * @param qq the value for s_t.QQ
     *
     * @mbggenerated
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Education
     *
     * @return the value of s_t.Education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Education
     *
     * @param education the value for s_t.Education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Province
     *
     * @return the value of s_t.Province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Province
     *
     * @param province the value for s_t.Province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Sname
     *
     * @return the value of s_t.Sname
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Sname
     *
     * @param sname the value for s_t.Sname
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.School
     *
     * @return the value of s_t.School
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.School
     *
     * @param school the value for s_t.School
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Profession
     *
     * @return the value of s_t.Profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Profession
     *
     * @param profession the value for s_t.Profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Topic
     *
     * @return the value of s_t.Topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Topic
     *
     * @param topic the value for s_t.Topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.Email
     *
     * @return the value of s_t.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.Email
     *
     * @param email the value for s_t.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}