package com.dao;

import com.pojo.ST;
import com.pojo.STExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface STMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int countByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int deleteByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idsT);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int insert(ST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int insertSelective(ST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    List<ST> selectByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    ST selectByPrimaryKey(Integer idsT);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ST record, @Param("example") STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ST record, @Param("example") STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ST record);


    ST insertByEmail(String email);
}